//
//  MySingleton.h
//  Jebbit
//
//  Created by Balaji Pandian on 12/24/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <EventKit/EventKit.h>
#import "UtilityMethods.h"

@interface MySingleton : NSObject

+ (MySingleton *) instance;
- (void)goBackward;
- (void)goForward;

@property(strong,nonatomic) NSDate *startDate;
@property(strong,nonatomic) NSDate *endDate;

// This is the 'root' for the time period. The start and end dates are generated by looking at the active date and the timePeriod. e.g. if active date is Wed 4th Jan, and time period is week, then start date will be found to be Mon 2nd Jan.
@property(strong,nonatomic) NSDate *activeDate;

/*
 0 : Custom,
 1 : Day,
 2 : Week,
 3 : Month
 */
@property(nonatomic) NSInteger timePeriod;

@end
